### ISSUE TITLE
Bug. JSException when calling marker.SetMap(null) to remove marker from map

### ISSUE THREAD

**Issue by MikeEvans** [rungwiroon/BlazorGoogleMaps#175]
I can't remove markers from my map. I've gone to check that I'm doing it right by referring to the demo project, but the problem happens there too.  

Running the ServerSideDemo project from the 1.5.2 commit (b4cb4ad) in Chrome 98.0.4758.102 (Official Build) (64-bit).  On the Map Marker List page, clicking "Add markers part 1" then "Remove all markers" throws this exception:

Microsoft.JSInterop.JSException: 'Cannot read properties of null (reading 'hasOwnProperty')
TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at Object.invoke (https://localhost:44386/_content/BlazorGoogleMaps/js/objectManager.js:419:29)
    at https://localhost:44386/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:44386/_framework/blazor.server.js:1:3475)
    at https://localhost:44386/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:44386/_framework/blazor.server.js:1:71987)
    at kt._processIncomingData (https://localhost:44386/_framework/blazor.server.js:1:70029)
    at vt.connection.onreceive (https://localhost:44386/_framework/blazor.server.js:1:64432)
    at WebSocket.o.onmessage (https://localhost:44386/_framework/blazor.server.js:1:48766)'

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.5.3
