### ISSUE TITLE
Bug: line in objectManager.js obj instanceof google.maps.places throws undefined exception 

### ISSUE THREAD

**Issue by funkysi1701** [rungwiroon/BlazorGoogleMaps#221]
I have been using BlazorGoogleMaps for a while and I recently upgraded from 2.3.1 to 2.4.1

After the upgrade I am seeing the following error in the browser console

[2022-11-29T10:53:11.980Z] Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'AutocompleteService')
TypeError: Cannot read properties of undefined (reading 'AutocompleteService')
    at Object.invoke (https://example.co.uk/_content/BlazorGoogleMaps/js/objectManager.js:517:52)
    at https://example.co.uk/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://example.co.uk/_framework/blazor.server.js:1:3475)
    at https://example.co.uk/_framework/blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://example.co.uk/_framework/blazor.server.js:1:72063)
    at kt._processIncomingData (https://example.co.uk/_framework/blazor.server.js:1:70105)
    at connection.onreceive (https://example.co.uk/_framework/blazor.server.js:1:64508)
    at o.onmessage (https://example.co.uk/_framework/blazor.server.js:1:48842)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args)
   at Example.Pages.Projects.ProjectDetailsBase.AddLocations() in D:\a\1\s\Example\Pages\Projects\ProjectDetails.razor.cs:line 426
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at GoogleMapsComponents.GoogleMap.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

The only change I made was to the csproj file and the update of BlazorGoogleMaps from 2.3.1 to 2.4.1

Do I need to make additional changes to my project to work with version 2.4.1 or is this a bug?

**Comment by valentasm1** [comment]
Does latest 2.4.2 nuget solve issue?
https://www.nuget.org/packages/BlazorGoogleMaps/2.4.2

**Comment by funkysi1701** [comment]
Yes 2.4.2 looks to have fixed this issue
