### ISSUE TITLE
Custom colors per geoJSON feature added to map data

### ISSUE THREAD

**Issue by asamite** [rungwiroon/BlazorGoogleMaps#245]
I have a number of polygons I pull from a database and build geojson objects (feature collections) and need to be able to change their color independently.  I have tagged each feature with an id. When I try to use the example from the ServerSideDemo (MapDataPage.razor) and try to modify it to get the feature and change the style, it gets a null value on the feature.  Any clue on how to get the feature I am looking for and apply a specific style to it.  I expect that I will have 5-10 differently styles feature collections on some pulls and all of the features will contain the same ID.  Been banging my head on this all day.  Below the code is the error I get.

    private async Task GetMapDataGeoJsonPolygon()
        {
            StyleOptions _style = new StyleOptions { StrokeColor = "black", StrokeWeight = 1, FillColor = "orange", FillOpacity = 0.3f };
            var jsonData = "{ \"type\": \"FeatureCollection\"," +
                           "  \"features\": [" +
                           "{ \"type\": \"Feature\"," +
                           " \"id\": 3," +
                           " \"properties\": { \"stroke\": \"#000000\", \"stroke-width\": 2, \"stroke-opacity\": 1 }, " +
                           " \"geometry\": {\"type\": \"Polygon\",  \"coordinates\": [ [ [ 151.219, -33.888], [151.23, -33.888], [151.23, -33.869], [ 151.219, -33.869], [ 151.219, -33.888]]]}}]}";
    
            await _map1.InteropObject.Data.AddGeoJson(jsonData);
            await _map1.InteropObject.Data.SetStyle(
	            new StyleOptions { 
		            StrokeColor = "magenta", 
		            StrokeWeight = 2, 
		            FillColor = "magenta", 
		            FillOpacity = 0.3f });
            Feature feature = await _map1.InteropObject.Data.GetFeatureById(3);
            await _map1.InteropObject.Data.OverrideStyle(feature, _style);
        }

[2023-02-23T08:52:21.592Z] Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Each parameter in the deserialization constructor on type 'GoogleMapsComponents.Maps.Data.Feature' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.. See InnerException for more details.
 ---> System.InvalidOperationException: Each parameter in the deserialization constructor on type 'GoogleMapsComponents.Maps.Data.Feature' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args)
   at Web.Pages.Map_data.GetMapDataGeoJsonPolygon() in E:\VisualStudio\B2M\Web\Pages\Map-data.razor:line 118
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by valentasm1** [comment]
First what catch my attention is this 
ThrowInvalidOperationException_ConstructorParameterIncompleteBinding
In many cases all classes which are seriazable to json must have parameterless constructor. Which Feature class dont have. I added empty one so serialization works, BUT Feature is not implement and i wont do that in any near future.
It needs returning json analyze and modify Feature class in c# accordingly. I dont have such time.

Sadly but you should do PR.
You should start at 
```
result = obj[functionToInvoke](...args2);
```
to see what is returned after you invoke
```
Feature feature = await _map1.InteropObject.Data.GetFeatureById(3);
```
Or smth like that.
