### ISSUE TITLE
JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.

### ISSUE THREAD

**Issue by ryanbuening** [rungwiroon/BlazorGoogleMaps#272]
In a Blazor Server app, starting with version 3.1.0, we are seeing the exception below in our logs. It seems to occur when a user navigates from a page that includes a map. Is there something that needs done in the component to properly dispose?

```
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args)
   at GoogleMapsComponents.JsObjectRef.InvokeAsync(String functionName, Object[] args)
   at GoogleMapsComponents.Maps.MapEventListener.RemoveAsync()
   at GoogleMapsComponents.Maps.MapEventListener.DisposeAsyncCore()
   at GoogleMapsComponents.Maps.MapEventListener.DisposeAsync()
   at GoogleMapsComponents.Maps.Extension.EventEntityBase.DisposeAsyncCore()
   at GoogleMapsComponents.Maps.Map.DisposeAsyncCore()
   at GoogleMapsComponents.Maps.Map.DisposeAsync()
   at GoogleMapsComponents.MapComponent.DisposeAsyncCore()
   at GoogleMapsComponents.MapComponent.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
```

**Comment by valentasm1** [comment]
I dont get any error in our server side demo. Maybe you see where is configuration difference?
https://github.com/rungwiroon/BlazorGoogleMaps/tree/master/ServerSideDemo

**Comment by valentasm1** [comment]
Maybe i need to do some steps to reproduce. Maybe you could reproduce in our server side demo

**Comment by turner11** [comment]
Was able to reproduce. 
Fixed in [this PR](https://github.com/rungwiroon/BlazorGoogleMaps/pull/273)

**Comment by valentasm1** [comment]
Strange issue, strange solution :).
https://www.nuget.org/packages/BlazorGoogleMaps/3.1.1

What do you think if we migrate all project from standart to .net6 (or even 7)?
There was such ideas for a long time.
