### ISSUE TITLE
Title misspelled

### ISSUE THREAD

**Issue by granstam-dev** [rungwiroon/BlazorGoogleMaps#31]
Marker.cs - row 207 (SetTilte)

**Getting an exception (await marker.SetTiltle("some text")):**
Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=obj[args[1]] is not a function
TypeError: obj[args[1]] is not a function
    at Object.invoke (http://localhost:52781/_content/BlazorGoogleMaps/objectManager.js:176:38)
    at http://localhost:52781/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:52781/_framework/blazor.server.js:8:31390)
    at http://localhost:52781/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:52781/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:52781/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://localhost:52781/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (http://localhost:52781/_framework/blazor.server.js:1:38091)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeWithDefaultCancellation>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at GoogleMapsComponents.Helper.<MyInvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Should probably be something like:**

        public Task SetTitle(string title)
        {
            return _jsObjectRef.InvokeAsync(
                "setTitle",
                title);
        }

**Comment by valentasm1** [comment]
Will review today later and letyou know. Thank you for fix suggestion.

**Comment by valentasm1** [comment]
Fixed
https://www.nuget.org/packages/BlazorGoogleMaps/0.5.8

**Comment by valentasm1** [comment]
Is it working as you expect?

**Comment by granstam-dev** [comment]
Yes, thank you!
