### ISSUE TITLE
Polyline getPath doesnt work and return path

### ISSUE THREAD

**Issue by granstam-dev** [rungwiroon/BlazorGoogleMaps#32]
Code:
```
 polylineOptions = new PolylineOptions()
                        {
                            Path = myRoute.ToArray(),
                            StrokeColor = "#0000FF",
                            Geodesic = true,
                            Clickable = true,
                            StrokeOpacity = 0.5F,
                            Map = _map.InteropObject
                        };

var routeLine = await Polyline.CreateAsync(_map.JsRuntime, polylineOptions);
var path = await routeLine.GetPath();
```

**Path is always null and a (handled) exception is thrown:**

Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=obj[args[1]] is not a function
TypeError: obj[args[1]] is not a function
    at Object.invoke (http://localhost:52781/_content/BlazorGoogleMaps/objectManager.js:176:38)
    at http://localhost:52781/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:52781/_framework/blazor.server.js:8:31390)
    at http://localhost:52781/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:52781/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (http://localhost:52781/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (http://localhost:52781/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (http://localhost:52781/_framework/blazor.server.js:1:38091)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeWithDefaultCancellation>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at GoogleMapsComponents.Helper.<MyInvokeAsync>d__2`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Enera.WorkMirror.BlazorAdminTool.Pages.JourneyMap.<PlotJourneyOnMap>d__20.MoveNext() 

The polyline is drawn in the map as it should. 
**If you fix this could you please also add a MapEventListener on Polyline so it is possible to handle mouse click on the polyline.**

**Comment by valentasm1** [comment]
It was returning array but our script was casting it to string.
I this change could be big one and brake things. As far as i tested it looks like everything ok.
Let me know if it workign now. 

https://www.nuget.org/packages/BlazorGoogleMaps/0.5.9

**Comment by granstam-dev** [comment]
Thank you, now it works as it should!

Have you looked at the other thing I asked for (to add a Task<MapEventListener> AddListener to Polyline, the same way that is done for Rectangle and for Marker)?

I have set the PolylineOption to Clickable and the mouse pointer changes when I move over the polyline in the map.
But I need to detect click and mouseover on the line (to change the color of the line and to open a InfoWindow) and I don't know how I can do this whitout an event listener. Or is it another way to achieve this?

**Comment by valentasm1** [comment]
Could you give other issue number or link?

I doubt that there is other way to capture clicked on polyline. Why you dont like this way?

**Comment by granstam-dev** [comment]
Sorry I didn't create a separate issue for this, it's in this issue(#32); my last sentance (in bold) in the description of the issue above.

There is no method like this for adding a listener in Polyline:
```
	public async Task<MapEventListener> AddListener(string eventName, Action handler)
        {
            var listenerRef = await _jsObjetRef.InvokeWithReturnedObjectRefAsync(
                "addListener", eventName, handler);

            return new MapEventListener(listenerRef);
        }

        public async Task<MapEventListener> AddListener<T>(string eventName, Action<T> handler)
        {
            var listenerRef = await _jsObjetRef.InvokeWithReturnedObjectRefAsync(
                "addListener", eventName, handler);

            return new MapEventListener(listenerRef);
        }
```

Thats why I want it so that I could add a listener for mouse events on the Polyline the same way that I can do for Marker (Rectangle):

```
var marker = await Marker.CreateAsync(_map1.JsRuntime);
await marker.AddListener("click", async () =>
       {
	        await infoWindow.SetContent(infoWindowContent);
                await infoWindow.SetPosition(pos);
                await infoWindow.Open(_map1.InteropObject);
       });
```

All object (PolyLine, Polygon, Circle...) should have Addlistener methods.

**Comment by valentasm1** [comment]
Sorry i havent seen that bold.
Updated lib.
Havent tested many cased only click.
Let me know if it works
https://www.nuget.org/packages/BlazorGoogleMaps/0.6.0

btw added event listener to polygon too

**Comment by valentasm1** [comment]
Missed circle. Added here
https://www.nuget.org/packages/BlazorGoogleMaps/0.6.1

**Comment by granstam-dev** [comment]
It works as it should, thank you. Keep up the good work!
