### ISSUE TITLE
Blazor web app demo

### ISSUE THREAD

**Issue by samcarrier** [rungwiroon/BlazorGoogleMaps#334]
Is there a demo or usage example or any kind of documentation for a blazor web app project?

I'm getting no visual and this error in debug output: 

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Blazor initializers
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by valentasm1** [comment]
Yes
Online working
https://rungwiroon.github.io/BlazorGoogleMaps/
Source
https://github.com/rungwiroon/BlazorGoogleMaps/tree/master/ClientSideDemo

I think there is detailed issue for you. Just need to dig log a bit more.
