### ISSUE TITLE
PlaceService GetDetails crash that JSON value could not be converted to GoogleMapsComponents.Maps.Places.PlaceResult[]

### ISSUE THREAD

**Issue by michaelcsikos** [rungwiroon/BlazorGoogleMaps#351]
In `ServerSideDemo` > `Services`, clicking on a suggestion location icon throws:

```
Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to GoogleMapsComponents.Maps.Places.PlaceResult[]. Path: $.results | LineNumber: 0 | BytePositionInLine: 12.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to GoogleMapsComponents.Maps.Places.PlaceResult[]. Path: $.results | LineNumber: 0 | BytePositionInLine: 12.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
```

This is affecting us in a production environment. Has something changed?

**Comment by valentasm1** [comment]
A lot of things change.  Do you have exact version?
I will try check today.

**Comment by michaelcsikos** [comment]
I'm using the current NuGet package, and I tried _beta_, _weekly_, _3.57_ for the Maps API.

**Comment by valentasm1** [comment]
I dont know when it changed, but it is older than November 06, 2023
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.6
