### ISSUE TITLE
Error when clicking on search button in MapAutocomplete.razor component

### ISSUE THREAD

**Issue by bwjunkie** [rungwiroon/BlazorGoogleMaps#70]
getting this JS console error  (VS Community 2019 16.7.5  Core 3.1)

blazor.server.js:19 

[2020-10-02T14:38:30.465Z] Error: Microsoft.JSInterop.JSException: Cannot read property 'Autocomplete' of undefined
TypeError: Cannot read property 'Autocomplete' of undefined
    at stringToFunction (https://localhost:44378/_content/BlazorGoogleMaps/objectManager.js:6:16)
    at Object.createObject (https://localhost:44378/_content/BlazorGoogleMaps/objectManager.js:171:27)
    at https://localhost:44378/_framework/blazor.server.js:8:31619
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44378/_framework/blazor.server.js:8:31587)
    at https://localhost:44378/_framework/blazor.server.js:1:20052
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44378/_framework/blazor.server.js:1:20022)
    at e.processIncomingData (https://localhost:44378/_framework/blazor.server.js:1:18006)
    at e.connection.onreceive (https://localhost:44378/_framework/blazor.server.js:1:11091)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args) in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\GoogleMapsComponents\Helper.cs:line 144
   at GoogleMapsComponents.JsObjectRef.CreateAsync(IJSRuntime jsRuntime, Guid guid, String functionName, Object[] args) in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\GoogleMapsComponents\JsObjectRef.cs:line 124
   at GoogleMapsComponents.Maps.Places.Autocomplete.CreateAsync(IJSRuntime jsRuntime, ElementReference inputField, AutocompleteOptions opts) in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\GoogleMapsComponents\Maps\Places\Autocomplete.cs:line 15
   at ServerSideDemo.Pages.MapAutocomplete.OnAfterMapInit() in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\ServerSideDemo\Pages\MapAutocomplete.razor:line 54
   at ServerSideDemo.Pages.MapAutocomplete.<BuildRenderTree>b__0_1() in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\ServerSideDemo\Pages\MapAutocomplete.razor:line 25
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at GoogleMapsComponents.GoogleMap.OnAfterRenderAsync(Boolean firstRender) in C:\Users\joshm\Downloads\BlazorGoogleMaps-master\BlazorGoogleMaps-master\GoogleMapsComponents\GoogleMap.razor:line 52
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by valentasm1** [comment]
Geting when and when?
Did you put scripts like mentioned in readme?

**Comment by bwjunkie** [comment]
Startup does not create a JS error.
Click "AutoComplete" on left bar shows map of Sydney (my API is working!)
I added in my API key

I did not need to add <script src="_content/BlazorGoogleMaps/objectManager.js"></script>
because it is already in the ServerSideDemo

**Comment by valentasm1** [comment]
I swear god it was working. 
Problem come from bad googleapis link declarations. multiple libraries should be separated by coma, not put multiple times. 
so this
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXXXX&v=3&libraries=places&libraries=visualization"></script>
Change to this
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=XXXXXXXXXXXXXXX&v=3&libraries=places,visualization"></script>
or pull
