### ISSUE TITLE
ServerSideDemo : Error: Could not find 'googleMapsObjectManager' in 'window'.

### ISSUE THREAD

**Issue by SamVanhoutte** [rungwiroon/BlazorGoogleMaps#98]
Hello, 

Thanks for this nice effort & library!  Eager to get my hands on it.
I wanted to get your ServerSideDemo running, but I get an exception, that I don't know how to solve:

Any idea on this?  (logs below)

Thanks again 

```
Microsoft.JSInterop.JSException: Could not find 'googleMapsObjectManager' in 'window'.
Error: Could not find 'googleMapsObjectManager' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:8:27732
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:8:27692)
    at https://localhost:5001/_framework/blazor.server.js:8:28402
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:28375)
    at https://localhost:5001/_framework/blazor.server.js:1:26303
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26273)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:24211)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at GoogleMapsComponents.Helper.MyInvokeAsync[TRes](IJSRuntime jsRuntime, String identifier, Object[] args) in /Users/samvanhoutte/git/BlazorGoogleMaps/GoogleMapsComponents/Helper.cs:line 174
   at GoogleMapsComponents.JsObjectRef.CreateAsync(IJSRuntime jsRuntime, Guid guid, String functionName, Object[] args) in /Users/samvanhoutte/git/BlazorGoogleMaps/GoogleMapsComponents/JsObjectRef.cs:line 124
   at GoogleMapsComponents.Maps.Map.CreateAsync(IJSRuntime jsRuntime, ElementReference mapDiv, MapOptions opts) in /Users/samvanhoutte/git/BlazorGoogleMaps/GoogleMapsComponents/Maps/Map.cs:line 29
   at ServerSideDemo.Pages.Maps.OnAfterRenderAsync(Boolean firstRender) in /Users/samvanhoutte/git/BlazorGoogleMaps/ServerSideDemo/Pages/Maps.razor:line 42
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'FNzS3Um2DnmghsG06uY1E1G0GRN0CSoWN_-OAajCsls'.
Microsoft.JSInterop.JSException: Could not find 'googleMapsObjectManager' in 'window'.

```

**Comment by valentasm1** [comment]
You just start application and get error right away?

**Comment by SamVanhoutte** [comment]
Thanks for your (extremely) fast response.  Appreciated.  I get the error when I navigate to a page that contains the map (in this case the maps): `https://localhost:5001/maps`

**Comment by SamVanhoutte** [comment]
I literally just did a git clone and changed nothing (tried with the baked in key, but also updated with my google maps api key)

**Comment by valentasm1** [comment]
Try this lounch config
Try differnet port
Is addblock working
Does other any pages working?

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:55631/",
      "sslPort": 44355
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "ServerSideDemo": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5000"
    }
  }
}
```

**Comment by SamVanhoutte** [comment]
> Try this lounch config

I'm using Jetbrains Rider on macOS , but I have used your package on another project, where it's successfully working.  So, I'm not sure if it's related to the above? 

> Try differnet port

I tried it on a new port, and the behavior is the same

> Is addblock working

No AddBlock, just native Google Chrome

> Does other any pages working?

Any page where the map control is used has the same issue

**Comment by valentasm1** [comment]
Do you see objectManager.js in file in inspector (mostly sources tab)?
Does file objectManager.js is copied to debug output location?

**Comment by SamVanhoutte** [comment]
So, when doing a clean + build, I don't see any objectManager.js in the tree of the ServerSideDemo (only in the ClientSideDemo debug folders)
Any idea how I can ensure that file gets copied ?

Cheers

**Comment by valentasm1** [comment]
Nah. Mostly it is related to rider or macos.

**Comment by SamVanhoutte** [comment]
okay, I'll close the issue, once I figured it out.  will update here in case someone else gets the same issue.
thanks for your support

**Comment by SamVanhoutte** [comment]
I tried launching it now from VsCode, and that worked immediately.  No idea on the **actual** root cause, but good enough for me.  Thanks again
